name: OWASP ZAP Scan Action
on: [push]
permissions:   #enable permission for default github token
  contents: read
  pull-requests: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable' #ghcr.io/zaproxy/zaproxy:stable
          target: 'http://testphp.vulnweb.com/' # can find more test urls from https://owasp.org/www-project-vulnerable-web-applications-directory/
          rules_file_name: .zap/rules.tsv
          cmd_options: '-a'
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable' #ghcr.io/zaproxy/zaproxy:stable
          target: 'http://testphp.vulnweb.com/' # can find more test urls from https://owasp.org/www-project-vulnerable-web-applications-directory/
          rules_file_name: .zap/rules.tsv
          cmd_options: '-a'